"""sync_schema_with_models

Revision ID: 0288693c52ac
Revises: ee03a12141fe
Create Date: 2025-12-24 12:44:53.036292

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0288693c52ac"
down_revision: Union[str, Sequence[str], None] = "ee03a12141fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_channel_meta_id"), table_name="channels")
    op.create_index(
        "idx_channel_meta_id", "channels", ["meta_phone_number_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_channel_meta_id", table_name="channels")
    op.create_index(
        op.f("idx_channel_meta_id"), "channels", ["meta_phone_number_id"], unique=True
    )
    # ### end Alembic commands ###
